-- Insert Emergent
INSERT INTO public.products (
  name,
  slug,
  category_type,
  db_fit,
  first_class_neon,
  first_class_supabase,
  byo_postgres,
  deploy_path,
  oss,
  pricing_model,
  ai_builder,
  designer_first,
  enterprise_ready,
  tags,
  overview_short,
  pros_short,
  cons_short,
  complexity_hint,
  difficulty_hint,
  use_case_category,
  url,
  avg_rating,
  vote_count
) VALUES (
  'Emergent',
  'emergent',
  'AI Builder',
  'BYO Postgres',
  false,
  false,
  true,
  'Cloud Managed',
  false,
  'freemium',
  true,
  false,
  false,
  'ai agent, fullstack, vibe coding, plain english, production-ready',
  'AI-powered vibe coding agent that builds full-stack, production-ready applications from plain English prompts in minutes.',
  'Simple natural language interface, full-stack apps, production-ready code, fast development',
  'Cloud-dependent, limited customization for complex requirements',
  2,
  2,
  'Full-Stack Apps',
  'https://app.emergent.sh',
  0,
  0
);

-- Insert MGX (MetaGPT X)
INSERT INTO public.products (
  name,
  slug,
  category_type,
  db_fit,
  first_class_neon,
  first_class_supabase,
  byo_postgres,
  deploy_path,
  oss,
  pricing_model,
  ai_builder,
  designer_first,
  enterprise_ready,
  tags,
  overview_short,
  pros_short,
  cons_short,
  complexity_hint,
  difficulty_hint,
  use_case_category,
  url,
  avg_rating,
  vote_count
) VALUES (
  'MGX (MetaGPT X)',
  'mgx',
  'AI Builder',
  'First-class Supabase',
  false,
  true,
  true,
  'Cloud Managed',
  false,
  'paid',
  true,
  false,
  false,
  'multi-agent, no-code, supabase, development workflow, requirement analysis',
  'Multi-agent AI platform simulating human software team workflow. Handles requirement analysis, planning, coding, testing, and deployment with specialized AI agents.',
  'Complete development pipeline, Supabase integration, multi-agent system, no coding required',
  'Paid only, less control over individual components, learning curve for agent workflow',
  3,
  2,
  'Full-Stack Apps',
  'https://mgx.dev',
  0,
  0
);

-- Insert Tempo
INSERT INTO public.products (
  name,
  slug,
  category_type,
  db_fit,
  first_class_neon,
  first_class_supabase,
  byo_postgres,
  deploy_path,
  oss,
  pricing_model,
  ai_builder,
  designer_first,
  enterprise_ready,
  tags,
  overview_short,
  pros_short,
  cons_short,
  complexity_hint,
  difficulty_hint,
  use_case_category,
  url,
  avg_rating,
  vote_count
) VALUES (
  'Tempo',
  'tempo-new',
  'AI Builder',
  'BYO Postgres',
  false,
  false,
  true,
  'Self-hosted',
  false,
  'freemium',
  true,
  true,
  false,
  'react, figma, drag-drop, design tool, collaboration, gitlab, claude',
  'Build React apps 10x faster with AI. Designer-developer collaboration platform with Figma-like drag-and-drop editor and AI code generation.',
  'Figma integration, visual drag-drop editor, GitLab/GitHub support, designer-friendly, MCP App Store',
  'React-only, limited to frontend-focused apps, requires understanding of React concepts',
  2,
  3,
  'Prototyping',
  'https://www.tempo.new',
  0,
  0
);