-- Insert Webdraw
INSERT INTO public.products (
  name,
  slug,
  category_type,
  db_fit,
  first_class_neon,
  first_class_supabase,
  byo_postgres,
  deploy_path,
  oss,
  pricing_model,
  ai_builder,
  designer_first,
  enterprise_ready,
  tags,
  overview_short,
  pros_short,
  cons_short,
  complexity_hint,
  difficulty_hint,
  use_case_category,
  url,
  avg_rating,
  vote_count
) VALUES (
  'Webdraw',
  'webdraw',
  'AI Builder',
  'No Database',
  false,
  false,
  false,
  'Self-hosted',
  false,
  'free',
  true,
  true,
  false,
  'sketch to code, visual builder, web apps, prototyping, no-code',
  'Turn sketches into web apps with zero coding experience. Genius UX that converts hand-drawn designs into functional websites.',
  'Free, incredibly simple UX, perfect for non-technical users, quick prototyping from sketches',
  'Limited to web apps, no backend/database support, basic functionality',
  1,
  1,
  'Prototyping',
  'https://webdraw.xyz',
  0,
  0
);

-- Insert Cline
INSERT INTO public.products (
  name,
  slug,
  category_type,
  db_fit,
  first_class_neon,
  first_class_supabase,
  byo_postgres,
  deploy_path,
  oss,
  pricing_model,
  ai_builder,
  designer_first,
  enterprise_ready,
  tags,
  overview_short,
  pros_short,
  cons_short,
  complexity_hint,
  difficulty_hint,
  use_case_category,
  url,
  avg_rating,
  vote_count
) VALUES (
  'Cline',
  'cline',
  'IDE Plugin',
  'BYO Postgres',
  false,
  false,
  true,
  'Local',
  true,
  'oss',
  true,
  false,
  false,
  'vscode, ai assistant, coding agent, large codebase, model agnostic',
  'VS Code plugin AI agent that works with large codebases. Supports any LLM and has runtime awareness for intelligent code assistance.',
  'Open source, model-agnostic, excellent for large projects, runtime-aware coding assistance',
  'Requires VS Code, developer-focused, steeper learning curve for non-coders',
  3,
  4,
  'Development',
  'https://github.com/cline/cline',
  0,
  0
);

-- Insert Steercode
INSERT INTO public.products (
  name,
  slug,
  category_type,
  db_fit,
  first_class_neon,
  first_class_supabase,
  byo_postgres,
  deploy_path,
  oss,
  pricing_model,
  ai_builder,
  designer_first,
  enterprise_ready,
  tags,
  overview_short,
  pros_short,
  cons_short,
  complexity_hint,
  difficulty_hint,
  use_case_category,
  url,
  avg_rating,
  vote_count
) VALUES (
  'Steercode',
  'steercode',
  'Mobile Builder',
  'No Database',
  false,
  false,
  false,
  'Cloud Managed',
  false,
  'freemium',
  true,
  false,
  false,
  'mobile app builder, react native, expo, voice prompts, no-code',
  'Mobile app that builds mobile apps from text or voice prompts. Handles full stack with Expo sharing for instant deployment.',
  'Build from your phone, voice/text prompts, instant sharing via Expo, beginner-friendly',
  'Mobile-only development environment, limited to simpler apps, requires Expo knowledge for advanced features',
  2,
  2,
  'Mobile Apps',
  'https://steercode.com',
  0,
  0
);