// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syxpdymopkpketmvybtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eHBkeW1vcGtwa2V0bXZ5YnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMzE0NzIsImV4cCI6MjA3NTYwNzQ3Mn0.3QRWQV1HBaoDW1zREkuT-U7Zwbtx-sUtgyaF_4G8sQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});